### ISSUE TITLE
download pages offline

### ISSUE THREAD

**Issue by fabrizioguillaro** [li-yanhao/masksim#1]
Hi, amazing work!

I am trying to download the weights but the provided link (https://cirrus.universite-paris-saclay.fr/s/bk8yEHntsbaHW5n/download/checkpoints.zip) looks like it's broken.
Same happens for the dataset link (https://cirrus.universite-paris-saclay.fr/s/2eabgG8fZy8nXME/download/train.zip)

Is there a mirror link I could use?
Thank you!

**Comment by li-yanhao** [comment]
Hi, 

Thanks for reporting the problem. Indeed the provided link no longer works as the cloud server of the university is down. You can use [this temporary link](https://zenodo.org/records/12570481/files/checkpoints.zip?download=1&preview=1) for downloading the weights. A new link will be updated on readme as soon as possible.

**Comment by fabrizioguillaro** [comment]
Thank you for providing a new link, however it currently says that I lack permissions

**Comment by li-yanhao** [comment]
Try [this link](https://filesender.renater.fr/?s=download&token=6f8aebd2-94bb-449b-9298-32ee45006a9c) then.

**Comment by fabrizioguillaro** [comment]
Yes it worked, thank you for your availability!

**Comment by fabrizioguillaro** [comment]
Hi, unfortunately the same happens when attempting to download the denoiser weights from  "https://cirrus.universite-paris-saclay.fr/s/AyZbytJAmEymJNb/download/model_best.th"

**Comment by li-yanhao** [comment]
Hi. Indeed this file is missing. Here is a temporary access [this link](https://filesender.renater.fr/?s=download&token=eec3644c-64f3-4055-9aa7-46e885946540), then you can import the weights manually.

**Comment by fabrizioguillaro** [comment]
thank you very much!

**Comment by li-yanhao** [comment]
Update: the dataset and checkpoints are available now in the new commit.
